CATALOGUE_HOST: catalogue-{{ env }}.rshopdaws84s.site
USER_HOST: user-{{ env }}.rshopdaws84s.site
CART_HOST: cart-{{ env }}.rshopdaws84s.site
SHIPPING_HOST: shipping-{{ env }}.rshopdaws84s.site
PAYMENT_HOST: payment-{{ env }}.rshopdaws84s.site