
- name: disabling the module
  ansible.builtin.command: dnf module disable nginx -y

- name: enabling the module
  ansible.builtin.command: dnf module enable nginx:1.24 -y


- name: install the nginx
  ansible.builtin.dnf:
    name: nginx
    state: present


- name: start and enable the service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes


- name: removing the default content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: creating the html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download the code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: extract or unzip the code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes 

- name: removing the default content
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: copy the nginx configuration
  ansible.builtin.copy:
    src: nginx.config
    dest: /etc/nginx/nginx.conf
  notify: 
    - Restart nginx


