- name: app setup
  include_role:
    name: common
    tasks_from: app_setup
    

- name: nodejs setup  
  include_role:
    name: common
    task_from: nodejs_setup


- name: copy the repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo


- name: install the mognodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host mongodb.rshopdaws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output


- name: print catalogue_output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load the products
  ansible.builtin.shell: mongosh --host mongodb.rshopdaws84s.site < /app/db/master-data.js
  when: catalogue_output.stdout | int < 0


- name: start the service
  include_role: common
  task_from:
    name: systemd_setup