- name: app setup
  include_role:
    name: common
    tasks_from: app_setup
    

- name: nodejs setup  
  include_role:
    name: common
    tasks_from: nodejs_setup


- name: copy the repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo


- name: install the mognodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check products loaded or not
  ansible.builtin.command: mongosh --host MONGODB_HOST--eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output
  ignore_errors: true
  ignore_unreachable: true

- name: print catalogue_output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"
  ignore_errors: true
  ignore_unreachable: true

- name: load the products
  ansible.builtin.shell: mongosh --host MONGODB_HOST< /app/db/master-data.js
  when: catalogue_output.stdout | int < 0
  ignore_errors: true
  ignore_unreachable: true

- name: start the service
  include_role: 
    name: common
    tasks_from: systemd_setup
  

# - name: Deployment
#   tags:
#     deployment 
#   import_role:
#     name: common
#     tasks_from: deployment