MYSQL_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/roboshop/mysql/mysql_root_password', region='us-east-1', decrypt=True ) }}"
# NEW (Use the variable passed from Terraform)
# MYSQL_PASSWORD: "{{ mysql_root_password }}"